name: Radio Javan Downloader

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download_song:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Radio Javan Downloader
        env:
          URL: ${{ secrets.RADIO_JAVAN_URL }}
        run: |
          python rj_downloader.py $URL
